name: Initial Setup & Partial Zipping

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GHCR
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Pull Docker image
      run: docker pull ghcr.io/your_username/your_image:tag

    - name: Run Initial Docker Processes
      run: |
        docker run -d --name session_container ghcr.io/your_username/your_image:tag
        # Simulate initial processes
        sleep 1200 # Sleep for 20 minutes
        # Ensure proper permissions
        docker exec session_container bash -c "chmod -R 777 /app/sessions"
        # Zip the sessions folder, ignoring unreadable files, and ensure workflow succeeds
        docker exec session_container bash -c "zip -r /app/partial_sessions.zip /app/sessions || true"

    - name: Copy Partial Zip to Runner
      run: docker cp session_container:/app/partial_sessions.zip partial_sessions.zip

    - name: Upload partial session data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: partial_session_data
        path: partial_sessions.zip
