name: Unzip Session Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to GitHub
      run: echo ${{ secrets.NEW_GITHUB_TOKEN }} | gh auth login --with-token

    - name: Get the latest successful run ID of Workflow 1
      id: get_run_id
      run: |
        LATEST_RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.NEW_GITHUB_TOKEN }}" "https://api.github.com/repos/your_username/your_repo/actions/workflows/initial_setup_partial_zipping.yml/runs?status=success&per_page=1" | jq -r '.workflow_runs[0].id')
        echo "LATEST_RUN_ID=${LATEST_RUN_ID}" >> $GITHUB_ENV

    - name: Get the artifact download URL
      id: get_artifact_url
      run: |
        if [ "${LATEST_RUN_ID}" != "null" ]; then
          LATEST_ARTIFACT_URL=$(curl -s -H "Authorization: token ${{ secrets.NEW_GITHUB_TOKEN }}" "https://api.github.com/repos/your_username/your_repo/actions/runs/${LATEST_RUN_ID}/artifacts" | jq -r '.artifacts[0].archive_download_url')
          echo "LATEST_ARTIFACT_URL=${LATEST_ARTIFACT_URL}" >> $GITHUB_ENV
        else
          echo "No successful runs found"
          exit 1
        fi

    - name: Download the latest artifact
      if: env.LATEST_ARTIFACT_URL != 'null'
      run: |
        curl -L -H "Authorization: token ${{ secrets.NEW_GITHUB_TOKEN }}" -o partial_sessions.zip "${LATEST_ARTIFACT_URL}"
        ls -lh partial_sessions.zip

    - name: Verify artifact download
      if: env.LATEST_ARTIFACT_URL != 'null'
      run: |
        if [ -f partial_sessions.zip ]; then
          echo "Download successful"
          unzip -l partial_sessions.zip
        else
          echo "Download failed"
          exit 1
        fi

    - name: Pull Docker image
      run: docker pull ghcr.io/your_username/your_image:tag

    - name: Run Docker container with session data
      if: env.LATEST_ARTIFACT_URL != 'null'
      run: docker run -d --name session_container -v ${{ github.workspace }}/partial_sessions.zip:/app/partial_sessions.zip ghcr.io/your_username/your_image:tag
